import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import { randomUUID } from 'node:crypto';
import { startBroker } from '../src/broker.js';
import { RpcClient, connect, frames, send } from '../src/transport.js';
const pause = ms => new Promise(r => setTimeout(r, ms));

test('broker preserves unknown outcomes, correlates late replies, and deduplicates across clients', async t => {
  const runtime = await fs.mkdtemp(path.join(os.tmpdir(), 'mcp9-broker-'));
  process.env.VIM9_MCP_RUNTIME = runtime;
  const broker = await startBroker({ requestTimeout: 80 });
  const editor = await connect();
  const messages = [];
  let session;
  frames(editor, msg => { messages.push(msg); if (msg.type === 'welcome') session = msg.session; });
  send(editor, { type: 'hello', role: 'vim', protocol: 1, pid: 42, cwd: '/tmp', version: 900 });
  const a = await RpcClient.open(), b = await RpcClient.open();
  t.after(async () => { a.close(); b.close(); editor.destroy(); broker.close(); await fs.rm(runtime, { recursive: true, force: true }); });
  for (let i = 0; i < 20 && !session; i++) await pause(5);
  assert.ok(session);
  const id = randomUUID();
  const input = { session, buffer: 'b1', revision: 'r1' };
  const [first, duplicate] = await Promise.all([a.call('save_buffer', input, id), b.call('save_buffer', input, id)]);
  assert.equal(first.code, 'timeout');
  assert.equal(duplicate.outcome, 'unknown');
  assert.equal(messages.filter(m => m.id === id).length, 1);
  send(editor, { type: 'response', id, result: { ok: true, revision: 'r2', id: 'domain-id' } });
  await pause(10);
  const status = await a.call('request_status', { request_id: id });
  assert.equal(status.state, 'completed');
  const cached = await b.call('save_buffer', input, id);
  assert.equal(cached.ok, true);
  assert.equal(cached.request_id, id, 'domain result must not overwrite transport correlation');
  assert.equal(cached.id, 'domain-id', 'domain IDs must survive independently of request IDs');
  assert.equal(messages.filter(m => m.id === id).length, 1);
  const cancelId = randomUUID();
  const queued = a.call('save_buffer', input, cancelId);
  await pause(10);
  await b.call('cancel_request', { request_id: cancelId });
  await pause(10);
  assert.ok(messages.some(m => m.type === 'cancel' && m.id === cancelId));
  send(editor, { type: 'response', id: cancelId, result: { ok: false, code: 'cancelled' } });
  assert.equal((await queued).code, 'cancelled');
  const lost = a.call('save_buffer', input);
  await pause(10);
  editor.destroy();
  assert.equal((await lost).outcome, 'unknown');
  assert.deepEqual((await a.call('list_sessions')).sessions, []);
});
